export const SEND_MESSAGE_REQUESTED = 'SEND_MESSAGE_REQUESTED';
export const SEND_MESSAGE_SUCCCESS = 'SEND_MESSAGE_SUCCCESS';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';
export const SEND_MESSAGE_SAGA = 'SEND_MESSAGE_SAGA';
export const MAKE_A_NEW_FRIEND = 'MAKE_A_NEW_FRINED';
export const SET_CHATS_LIST = 'SET_CHATS_LIST';
export const MAKING_A_NEW_FRIEND = 'MAKING_A_NEW_FRIEND';
export const MAKING_A_NEW_FRIEND_DONE = 'MAKING_A_NEW_FRIEND_DONE';

export const GET_ROOM_CHATS_REQUEST = 'GET_ROOM_CHATS_REQUEST';
export const GET_ROOM_CHATS_SUCCESS = 'GET_ROOM_CHATS_SUCCESS';
export const GET_ROOM_CHATS_FAILED = 'GET_ROOM_CHATS_FAILED';
export const GET_ROOM_CHATS_REQUEST_SAGA = 'GET_ROOM_CHATS_REQUEST_SAGA';
// user actions
export const GET_USER_DETAILS_BY_USERNAME = 'GET_USER_DETAILS_BY_USERNAME';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const GET_USER_NAME_FROM_LOCAL_STORAGE =
  'GET_USER_NAME_FROM_LOCAL_STORAGE';
export const SET_USER_DETAILS_TO_REDUX = 'SET_USER_DETAILS_TO_REDUX';
export const SET_USER_DETAILS_UPDATING = 'SET_USER_DETAILS_UPDATING';
export const SET_USER_DETAILS_UPDATED = 'SET_USER_DETAILS_UPDATED';
export const CHECK_AND_UPDATE_USER_AUTH_STATUS =
  'CHECK_AND_UPDATE_USER_AUTH_STATUS';
export const SET_USER_AUTH_STATUS_LOGOUT = 'SET_USER_AUTH_STATUS_LOGOUT';
export const CHECK_OR_CREATE_USERDETAILS_FROM_FIREBASE =
  'CHECK_OR_CREATE_USERDETAILS_FROM_FIREBASE';
export const GET_USER_DETAILS_FROM_FIREBASE = 'GET_USER_DETAILS_FROM_FIREBASE';
export const SET_USER_DETAILS_FROM_FIREBASE = 'SET_USER_DETAILS_FROM_FIREBASE';
