export const SEND_MESSAGE = 'SEND_MESSAGE';

// user actions
export const GET_USER_DETAILS_BY_USERNAME = 'GET_USER_DETAILS_BY_USERNAME';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const GET_USER_NAME_FROM_LOCAL_STORAGE =
  'GET_USER_NAME_FROM_LOCAL_STORAGE';
export const SET_USER_NAME_SAGA = 'SET_USER_NAME_SAGA';
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_DETAILS_UPDATING = 'SET_USER_DETAILS_UPDATING';
export const SET_USER_DETAILS_UPDATED = 'SET_USER_DETAILS_UPDATED';
export const CHECK_AND_UPDATE_USER_AUTH_STATUS =
  'CHECK_AND_UPDATE_USER_AUTH_STATUS';
export const SET_USER_AUTH_STATUS_LOGOUT = 'SET_USER_AUTH_STATUS_LOGOUT';
