export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SET_CHATS_LIST = 'SET_CHATS_LIST';
// user actions
export const GET_USER_DETAILS_BY_USERNAME = 'GET_USER_DETAILS_BY_USERNAME';
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const GET_USER_NAME_FROM_LOCAL_STORAGE =
  'GET_USER_NAME_FROM_LOCAL_STORAGE';
export const SET_USER_DETAILS_TO_REDUX = 'SET_USER_DETAILS_TO_REDUX';
export const SET_USER_DETAILS_UPDATING = 'SET_USER_DETAILS_UPDATING';
export const SET_USER_DETAILS_UPDATED = 'SET_USER_DETAILS_UPDATED';
export const CHECK_AND_UPDATE_USER_AUTH_STATUS =
  'CHECK_AND_UPDATE_USER_AUTH_STATUS';
export const SET_USER_AUTH_STATUS_LOGOUT = 'SET_USER_AUTH_STATUS_LOGOUT';
export const CHECK_OR_CREATE_USERDETAILS_FROM_FIREBASE =
  'CHECK_OR_CREATE_USERDETAILS_FROM_FIREBASE';
export const GET_USER_DETAILS_FROM_FIREBASE = 'GET_USER_DETAILS_FROM_FIREBASE';
export const SET_USER_DETAILS_FROM_FIREBASE = 'SET_USER_DETAILS_FROM_FIREBASE';
